services:
  postgres:
    image: postgres:17

    container_name: search-typeahead-postgres

    environment:
      POSTGRES_DB: search_typeahead
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-1:
    image: redis:7.4-alpine
    container_name: search-typeahead-redis-1
    ports:
      - "6379:6379"

  redis-2:
    image: redis:7.4-alpine
    container_name: search-typeahead-redis-2
    ports:
      - "6380:6379"

  redis-3:
    image: redis:7.4-alpine
    container_name: search-typeahead-redis-3
    ports:
      - "6381:6379"

volumes:
  postgres_data:
